version: '3.5'

services:
  backend:
    container_name: backend
    image: backend:1.0.0
    build:
      context: ./
      dockerfile: backend/Dockerfile
    volumes:
      - /Users/arturo.duquem/Downloads:/home/images
    command: [python, backend.py]

  ui:
    container_name: interface
    image: interface:1.0.0
    build:
      context: ./
      dockerfile: interface/Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /Users/arturo.duquem/Downloads:/home/images
    environment:
      - DISPLAY=192.168.1.5:0
    command: [python, interface.py]